fix: styling issue on landing page
base-org/onchainsummer.xyz pull request #192
Opened 2023-08-10 18:20 UTC by ximxim

## Description

Collection section was showing even tho there were no remain drops for the partner. This PR fixes that style issue.

| Before | After |
| ------ | ------ |
| ![image](https://github.com/base-org/onchainsummer.xyz/assets/6590647/6be7e10c-2be2-4c77-88dd-c52c946a1abe) | ![image](https://github.com/base-org/onchainsummer.xyz/assets/6590647/27d8851d-5f65-4fde-bd19-de6fcdfdab8d) |

2023-08-10 22:36 UTC, AshishYelekar commented
@ximxim @lauchness this is not functioning as expected actually. That issue was happening because the mirror digest wasn't rendering not because the carousel was missing. IF we're going to merge we should do this based on article / digest presence only.

For example, this is a bug: https://onchainsummer-xyz-git-azim-fix-empty-collection-base-org.vercel.app/?spoofDate=2023-08-09

2023-08-10 22:36 UTC, AshishYelekar requested changes
See main comment

2023-08-10 22:36 UTC, cb-heimdall commented
Review Error for AshishYelekar @ 2023-08-10 22:36:58 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

2023-08-11 03:45 UTC, wilsoncusack commented
closing as not clear needs to merge. If you reopen please make title more clear/easier to QA/link ticket if you can :)

2023-08-11 03:45 UTC, closed without merging